#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ DRAG_REPO == "DRAGON🐲" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    elif [[ DRAG_REPO == "🐲DRAGON" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    elif [[ DRAG_REPO =~ $regex ]]
    then
        if [[ DRAG_REPO_BRANCH ]]
        then
            echo "${DRAG_REPO}/archive/${DRAG_REPO_BRANCH}.zip"
        else
            echo "${DRAG_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="mybot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    DRAGPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd DRAGPATH
    echo "  • Starting DRAGON🐲 BY SHAIL •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m dragbot
}

start_bot
